server {
    listen 80;
    root /usr/share/nginx/html;

    location /gold/assets/ {
        try_files $uri =404;
    }

    location /gold/ {
        try_files $uri /gold/index.html;
    }

    location / {
        return 301 /gold/;
    }
}
